In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [4]:
df=pd.read_csv("Food delivery.csv")

In [5]:
df.head()

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken(min)
0,0x4607,INDORES13DEL02,37,4.9,22.745049,75.892471,22.765049,75.912471,19-03-2022,11:30:00,11:45:00,conditions Sunny,High,2,Snack,motorcycle,0,No,Urban,(min) 24
1,0xb379,BANGRES18DEL02,34,4.5,12.913041,77.683237,13.043041,77.813237,25-03-2022,19:45:00,19:50:00,conditions Stormy,Jam,2,Snack,scooter,1,No,Metropolitian,(min) 33
2,0x5d6d,BANGRES19DEL01,23,4.4,12.914264,77.678400,12.924264,77.688400,19-03-2022,08:30:00,08:45:00,conditions Sandstorms,Low,0,Drinks,motorcycle,1,No,Urban,(min) 26
3,0x7a6a,COIMBRES13DEL02,38,4.7,11.003669,76.976494,11.053669,77.026494,05-04-2022,18:00:00,18:10:00,conditions Sunny,Medium,0,Buffet,motorcycle,1,No,Metropolitian,(min) 21
4,0x70a2,CHENRES12DEL01,32,4.6,12.972793,80.249982,13.012793,80.289982,26-03-2022,13:30:00,13:45:00,conditions Cloudy,High,1,Snack,scooter,1,No,Metropolitian,(min) 30

In [6]:
df.tail

<bound method NDFrame.tail of             ID Delivery_person_ID Delivery_person_Age Delivery_person_Ratings  \
0      0x4607     INDORES13DEL02                   37                     4.9
1      0xb379     BANGRES18DEL02                   34                     4.5
2      0x5d6d     BANGRES19DEL01                   23                     4.4
3      0x7a6a    COIMBRES13DEL02                   38                     4.7
4      0x70a2     CHENRES12DEL01                   32                     4.6
...        ...                ...                 ...                     ...
45588  0x7c09      JAPRES04DEL01                   30                     4.8
45589  0xd641      AGRRES16DEL01                   21                     4.6
45590  0x4f8d     CHENRES08DEL03                   30                     4.9
45591  0x5eee    COIMBRES11DEL01                   20                     4.7
45592  0x5fb2   RANCHIRES09DEL02                   23                     4.9

       Restaurant_latitude  Restaurant_longitude  Delivery_location_latitude  \
0                22.745049             75.892471                   22.765049
1                12.913041             77.683237                   13.043041
2                12.914264             77.678400                   12.924264
3                11.003669             76.976494                   11.053669
4                12.972793             80.249982                   13.012793
...                    ...                   ...                         ...
45588            26.902328             75.794257                   26.912328
45589             0.000000              0.000000                    0.070000
45590            13.022394             80.242439                   13.052394
45591            11.001753             76.986241                   11.041753
45592            23.351058             85.325731                   23.431058

       Delivery_location_longitude  Order_Date Time_Orderd Time_Order_picked  \
0                        75.912471  19-03-2022    11:30:00          11:45:00
1                        77.813237  25-03-2022    19:45:00          19:50:00
2                        77.688400  19-03-2022    08:30:00          08:45:00
3                        77.026494  05-04-2022    18:00:00          18:10:00
4                        80.289982  26-03-2022    13:30:00          13:45:00
...                            ...         ...         ...               ...
45588                    75.804257  24-03-2022    11:35:00          11:45:00
45589                     0.070000  16-02-2022    19:55:00          20:10:00
45590                    80.272439  11-03-2022    23:50:00          00:05:00
45591                    77.026241  07-03-2022    13:35:00          13:40:00
45592                    85.405731  02-03-2022    17:10:00          17:15:00

           Weatherconditions Road_traffic_density  Vehicle_condition  \
0           conditions Sunny                High                   2
1          conditions Stormy                 Jam                   2
2      conditions Sandstorms                 Low                   0
3           conditions Sunny              Medium                   0
4          conditions Cloudy                High                   1
...                      ...                  ...                ...
45588       conditions Windy                High                   1
45589       conditions Windy                 Jam                   0
45590      conditions Cloudy                 Low                   1
45591      conditions Cloudy                High                   0
45592         conditions Fog              Medium                   2

      Type_of_order Type_of_vehicle multiple_deliveries Festival  \
0            Snack      motorcycle                    0      No
1            Snack         scooter                    1      No
2           Drinks      motorcycle                    1      No
3           Buffet      motorcycle                    1      No
4            Snack         scooter                    1      No
...             ...             ...                 ...      ...
45588         Meal      motorcycle                    0      No
45589       Buffet      motorcycle                    1      No
45590       Drinks         scooter                    0      No
45591        Snack      motorcycle                    1      No
45592        Snack         scooter                    1      No

                 City Time_taken(min)
0              Urban         (min) 24
1      Metropolitian         (min) 33
2              Urban         (min) 26
3      Metropolitian         (min) 21
4      Metropolitian         (min) 30
...               ...             ...
45588  Metropolitian         (min) 32
45589  Metropolitian         (min) 36
45590  Metropolitian         (min) 16
45591  Metropolitian         (min) 26
45592  Metropolitian         (min) 36

[45593 rows x 20 columns]>

In [7]:
df.tail()

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken(min)
45588,0x7c09,JAPRES04DEL01,30,4.8,26.902328,75.794257,26.912328,75.804257,24-03-2022,11:35:00,11:45:00,conditions Windy,High,1,Meal,motorcycle,0,No,Metropolitian,(min) 32
45589,0xd641,AGRRES16DEL01,21,4.6,0.000000,0.000000,0.070000,0.070000,16-02-2022,19:55:00,20:10:00,conditions Windy,Jam,0,Buffet,motorcycle,1,No,Metropolitian,(min) 36
45590,0x4f8d,CHENRES08DEL03,30,4.9,13.022394,80.242439,13.052394,80.272439,11-03-2022,23:50:00,00:05:00,conditions Cloudy,Low,1,Drinks,scooter,0,No,Metropolitian,(min) 16
45591,0x5eee,COIMBRES11DEL01,20,4.7,11.001753,76.986241,11.041753,77.026241,07-03-2022,13:35:00,13:40:00,conditions Cloudy,High,0,Snack,motorcycle,1,No,Metropolitian,(min) 26
45592,0x5fb2,RANCHIRES09DEL02,23,4.9,23.351058,85.325731,23.431058,85.405731,02-03-2022,17:10:00,17:15:00,conditions Fog,Medium,2,Snack,scooter,1,No,Metropolitian,(min) 36

In [8]:
df.shape

(45593, 20)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45593 entries, 0 to 45592
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ID                           45593 non-null  object
 1   Delivery_person_ID           45593 non-null  object
 2   Delivery_person_Age          45593 non-null  object
 3   Delivery_person_Ratings      45593 non-null  object
 4   Restaurant_latitude          45593 non-null  float64
 5   Restaurant_longitude         45593 non-null  float64
 6   Delivery_location_latitude   45593 non-null  float64
 7   Delivery_location_longitude  45593 non-null  float64
 8   Order_Date                   45593 non-null  object
 9   Time_Orderd                  45593 non-null  object
 10  Time_Order_picked            45593 non-null  object
 11  Weatherconditions            45593 non-null  object
 12  Road_traffic_density         45593 non-null  object
 13  Vehicle_condition            45593 non-null  int64
 14  Type_of_order                45593 non-null  object
 15  Type_of_vehicle              45593 non-null  object
 16  multiple_deliveries          45593 non-null  object
 17  Festival                     45593 non-null  object
 18  City                         45593 non-null  object
 19  Time_taken(min)              45593 non-null  object
dtypes: float64(4), int64(1), object(15)
memory usage: 7.0+ MB

In [10]:
df.columns

Index(['ID', 'Delivery_person_ID', 'Delivery_person_Age',
       'Delivery_person_Ratings', 'Restaurant_latitude',
       'Restaurant_longitude', 'Delivery_location_latitude',
       'Delivery_location_longitude', 'Order_Date', 'Time_Orderd',
       'Time_Order_picked', 'Weatherconditions', 'Road_traffic_density',
       'Vehicle_condition', 'Type_of_order', 'Type_of_vehicle',
       'multiple_deliveries', 'Festival', 'City', 'Time_taken(min)'],
      dtype='object')